# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QOKsBRTTnXPd9MGin02Jxxa0t1BB7T7
"""

from datetime import date, datetime
import sys
import sqlite3
from sqlite3 import Error
import datetime
import openpyxl
import csv
import re